### ISSUE TITLE
drop down nav bottom border

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#36]
Please maintain the 1px grey border on the bottom of the drop down. Screenshot of error.
Tested Chrome / Mac

![image](https://cloud.githubusercontent.com/assets/4900157/9989187/ce9f4e76-6099-11e5-8ebe-dbdb8d129979.png)

**Comment by atulnarang** [comment]
please check now

**Comment by bradcbennett** [comment]
The bottom border looks good. But now there seems to be an issue with the right border of the element above the last element sticking out by a pixel (Chrome / Mac)

![image](https://cloud.githubusercontent.com/assets/4900157/9991119/91170858-60aa-11e5-86a4-0ccf688e9b71.png)

**Comment by atulnarang** [comment]
Fixed, please check

**Comment by bradcbennett** [comment]
Bottom border seems fixed. 
Right border is still incorrect (Chrome / Mac)

**Comment by atulnarang** [comment]
Can you please try clearing your cache Brad? It works fine on Yosemite/Chrome and Windows.

**Comment by bradcbennett** [comment]
Cleared cache and tested Firefox / Mac.
extra pixel still appears on roll over per screen shot below.

![image](https://cloud.githubusercontent.com/assets/4900157/10009455/907412e4-6120-11e5-8944-682c3a861fea.png)

**Comment by atulnarang** [comment]
This has been fixed, please check again.
